name: Django CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15 # Usa la versión que tengas instalada
        env:
          POSTGRES_DB: db_test_farmacia
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
        ports:
          - 5432:5432
        # Esperar a que postgres esté listo antes de iniciar los tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14.2' # Ajusta a tu versión

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest
      env:
        # Aquí puedes pasar variables de entorno necesarias para tus tests
        DEBUG: "False"
        SECRET_KEY: "clave-insegura-ci-test"
        ALLOWED_HOST: "localhost,127.0.0.1"
        DATABASE_URL: "postgres://user_ci:password_ci@localhost:5432/db_ci"