# Generated by Django 6.0 on 2025-12-30 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Laboratorio')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, verbose_name='Componente Activo / Descripción')),
                ('cantidad_mg', models.PositiveIntegerField(help_text='Ej: 500 para 500mg', verbose_name='Miligramos (mg)')),
                ('cantidad_capsulas', models.PositiveIntegerField(help_text='Ej: 10, 20, 30 comprimidos', verbose_name='Unidades por Caja')),
                ('es_bioequivalente', models.BooleanField(default=False, verbose_name='Es Bioequivalente')),
                ('codigo_serie', models.CharField(max_length=100, unique=True, verbose_name='Código de Barras / SKU')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos', to='modulo_principal.laboratorio')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, verbose_name='Serie / Lote Fabricante')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Disponible')),
                ('defectuoso', models.BooleanField(default=False, help_text='Marcar si el lote tiene alerta sanitaria')),
                ('activo', models.BooleanField(default=True, help_text='Desactiva el lote manualmente si es necesario')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='modulo_principal.medicamento')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('medicamento', 'codigo_lote')},
            },
        ),
    ]
