# Generated by Django 6.0 on 2026-02-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_serie',
            field=models.CharField(max_length=13, unique=True, verbose_name='Código de Barras / SKU'),
        ),
    ]
