# Generated by Django 6.0 on 2026-02-13 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_principal', '0002_alter_producto_codigo_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado del lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='defectuoso',
            field=models.BooleanField(default=False, help_text='Lote con alerta sanitaria'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha_creacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='modulo_principal.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_capsulas',
            field=models.PositiveIntegerField(verbose_name='Unidades por Caja'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_mg',
            field=models.PositiveIntegerField(verbose_name='Miligramos (mg)'),
        ),
    ]
